---
name: Algorithm-MedianSelect-XS
version: 0.14
author:
  - Steven Schubiger <schubiger@cpan.org>
abstract: Median finding algorithm
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  DynaLoader: 0
  Exporter: 0
  XSLoader: 0
recommends:
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
build_requires:
  Test::More: 0
provides:
  Algorithm::MedianSelect::XS:
    file: lib/Algorithm/MedianSelect/XS.pm
    version: 0.14
generated_by: Module::Build version 0.2703
