---
name: Algorithm-MedianSelect-XS
version: 0.12
author:
  - Steven Schubiger <schubiger@cpan.org>
abstract: Median finding algorithm
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Exporter: 0
  XSLoader: 0
build_requires:
  Test::More: 0
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
provides:
  Algorithm::MedianSelect::XS:
    file: lib/Algorithm/MedianSelect/XS.pm
    version: 0.12
generated_by: Module::Build version 0.2703
